"""
AlertLogic Informant Service — Notable events reporting service (v1).

The Informant service surfaces "notable events" (health/status messages
generated by the Alert Logic platform) for an account or a specific
deployment.  It is a Cloud Insight-era service whose API documentation
lives at:

    https://console.cloudinsight.alertlogic.com/api/informant/

There are two retrieval endpoints:

    GET /informant/v1/{account_id}/messages
    GET /informant/v1/{account_id}/deployment/{deployment_id}/messages

Both support the same pagination model: a forward-only cursor via
`continuation_id`, a `since` epoch-seconds filter, and a `limit` (1-200,
default 50).

Service host: the default Cloud Insight API base URL
    https://api.cloudinsight.alertlogic.com
No dedicated per-service hostname — responses come from the shared
api.cloudinsight.alertlogic.com endpoint used by the default base_url.

Source: reverse-engineered from
    https://console.cloudinsight.alertlogic.com/api/informant/api_data.js
    (apiDoc v0.12.1 — Informant Service 1.0.0, "Notable events reporting service")
"""
import os
from typing import Annotated, Optional
from pydantic import Field
from mcp.server import FastMCP
from modules.base import BaseModule


class InformantModule(BaseModule):
    """Informant v1: account-level and deployment-level notable-event messages."""

    def __init__(self):
        super().__init__()
        # The Informant service is hosted on the same base URL as the rest of
        # the Cloud Insight API (api.cloudinsight.alertlogic.com).  An env
        # override is provided for completeness / future migration.
        self.service_hosts["informant"] = os.environ.get(
            "ALERTLOGIC_INFORMANT_BASE_URL",
            self.base_url,  # falls back to https://api.cloudinsight.alertlogic.com
        )

    def register_tools(self, server: FastMCP):
        self._add_tool(
            server,
            self.informant_get_account_messages,
            "informant_get_account_messages",
            "Retrieve notable-event messages for an account from the Alert Logic Informant service",
        )
        self._add_tool(
            server,
            self.informant_get_deployment_messages,
            "informant_get_deployment_messages",
            "Retrieve notable-event messages scoped to a specific deployment from the Alert Logic Informant service",
        )

    # ------------------------------------------------------------------ #
    #  Endpoint 1 — Account-level messages                               #
    #  GET /informant/v1/{account_id}/messages                           #
    # ------------------------------------------------------------------ #

    def informant_get_account_messages(
        self,
        account_id: Annotated[Optional[str], Field(
            description=(
                "Alert Logic account ID. Defaults to the account associated with the "
                "configured API key (ALERTLOGIC_ACCOUNT_ID)."
            )
        )] = None,
        since: Annotated[Optional[int], Field(
            description=(
                "Unix epoch timestamp (seconds). Only messages with a timestamp "
                "strictly greater than this value are returned. Must be a "
                "non-negative integer. Omit to receive the most recent messages."
            ),
            ge=0,
        )] = None,
        limit: Annotated[Optional[int], Field(
            description=(
                "Maximum number of messages to return in a single call. "
                "Accepted range: 1–200. Defaults to 50 when omitted."
            ),
            ge=1,
            le=200,
        )] = None,
        continuation_id: Annotated[Optional[str], Field(
            description=(
                "Pagination cursor returned as `continuation_id` in a previous response. "
                "When supplied, `since` and `limit` must be omitted — the server "
                "rejects requests that combine a continuation token with other "
                "query parameters."
            )
        )] = None,
    ) -> dict:
        """Retrieve notable-event messages for an account.

        Returns a dict with:
          - messages       (list)  – list of Informant message objects
          - total_count    (int)   – total messages matching the query
          - continuation_id (str, optional) – pass to the next call to page forward

        Pagination note: `continuation_id` is mutually exclusive with `since`
        and `limit`.  To paginate, call again with only continuation_id set.

        GET /informant/v1/{account_id}/messages
        """
        params: dict = {}
        if continuation_id is not None:
            # When paginating, only the continuation token is allowed.
            params["continuation_id"] = continuation_id
        else:
            if since is not None:
                params["since"] = since
            if limit is not None:
                params["limit"] = limit

        return self._get_at(
            "informant",
            "/informant/v1/{account_id}/messages",
            account_id=account_id,
            params=params or None,
        )

    # ------------------------------------------------------------------ #
    #  Endpoint 2 — Deployment-scoped messages                           #
    #  GET /informant/v1/{account_id}/deployment/{deployment_id}/messages #
    # ------------------------------------------------------------------ #

    def informant_get_deployment_messages(
        self,
        deployment_id: Annotated[str, Field(
            description=(
                "Alert Logic deployment ID.  Scopes the query to notable events "
                "that belong to a single deployment within the account."
            )
        )],
        account_id: Annotated[Optional[str], Field(
            description=(
                "Alert Logic account ID. Defaults to the account associated with the "
                "configured API key (ALERTLOGIC_ACCOUNT_ID)."
            )
        )] = None,
        since: Annotated[Optional[int], Field(
            description=(
                "Unix epoch timestamp (seconds). Only messages with a timestamp "
                "strictly greater than this value are returned. Must be a "
                "non-negative integer. Omit to receive the most recent messages."
            ),
            ge=0,
        )] = None,
        limit: Annotated[Optional[int], Field(
            description=(
                "Maximum number of messages to return in a single call. "
                "Accepted range: 1–200. Defaults to 50 when omitted."
            ),
            ge=1,
            le=200,
        )] = None,
        continuation_id: Annotated[Optional[str], Field(
            description=(
                "Pagination cursor returned as `continuation_id` in a previous response. "
                "When supplied, `since` and `limit` must be omitted — the server "
                "rejects requests that combine a continuation token with other "
                "query parameters."
            )
        )] = None,
    ) -> dict:
        """Retrieve notable-event messages scoped to a specific deployment.

        Returns the same shape as informant_get_account_messages but filtered
        to the given deployment:
          - messages       (list)  – list of Informant message objects
          - total_count    (int)   – total messages matching the query
          - continuation_id (str, optional) – pass to the next call to page forward

        Pagination note: `continuation_id` is mutually exclusive with `since`
        and `limit`.

        GET /informant/v1/{account_id}/deployment/{deployment_id}/messages
        """
        params: dict = {}
        if continuation_id is not None:
            params["continuation_id"] = continuation_id
        else:
            if since is not None:
                params["since"] = since
            if limit is not None:
                params["limit"] = limit

        return self._get_at(
            "informant",
            f"/informant/v1/{{account_id}}/deployment/{deployment_id}/messages",
            account_id=account_id,
            params=params or None,
        )


def setup(server: FastMCP):
    mod = InformantModule()
    mod.register_tools(server)
